// Generated by Dagger (https://dagger.dev).
package com.prospective.tractorplus.ui.common;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NavigationController_Factory implements Factory<NavigationController> {
  @Override
  public NavigationController get() {
    return newInstance();
  }

  public static NavigationController_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static NavigationController newInstance() {
    return new NavigationController();
  }

  private static final class InstanceHolder {
    private static final NavigationController_Factory INSTANCE = new NavigationController_Factory();
  }
}
