// Generated by Dagger (https://dagger.dev).
package com.panaceasoft.psbuyandsell.ui.item.promote;

import android.content.SharedPreferences;
import androidx.lifecycle.ViewModelProvider;
import com.panaceasoft.psbuyandsell.ui.common.NavigationController;
import com.panaceasoft.psbuyandsell.ui.common.PSAppCompactActivity_MembersInjector;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ItemPromoteActivity_MembersInjector implements MembersInjector<ItemPromoteActivity> {
  private final Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider;

  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  private final Provider<NavigationController> navigationControllerProvider;

  private final Provider<SharedPreferences> prefProvider;

  public ItemPromoteActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<SharedPreferences> prefProvider) {
    this.dispatchingAndroidInjectorProvider = dispatchingAndroidInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.navigationControllerProvider = navigationControllerProvider;
    this.prefProvider = prefProvider;
  }

  public static MembersInjector<ItemPromoteActivity> create(
      Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<SharedPreferences> prefProvider) {
    return new ItemPromoteActivity_MembersInjector(dispatchingAndroidInjectorProvider, viewModelFactoryProvider, navigationControllerProvider, prefProvider);
  }

  @Override
  public void injectMembers(ItemPromoteActivity instance) {
    PSAppCompactActivity_MembersInjector.injectDispatchingAndroidInjector(instance, dispatchingAndroidInjectorProvider.get());
    PSAppCompactActivity_MembersInjector.injectViewModelFactory(instance, viewModelFactoryProvider.get());
    PSAppCompactActivity_MembersInjector.injectNavigationController(instance, navigationControllerProvider.get());
    injectPref(instance, prefProvider.get());
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.item.promote.ItemPromoteActivity.pref")
  public static void injectPref(ItemPromoteActivity instance, SharedPreferences pref) {
    instance.pref = pref;
  }
}
