// Generated by Dagger (https://dagger.dev).
package com.panaceasoft.psbuyandsell.ui.common;

import android.content.SharedPreferences;
import androidx.lifecycle.ViewModelProvider;
import com.panaceasoft.psbuyandsell.utils.Connectivity;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PSFragment_MembersInjector implements MembersInjector<PSFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  private final Provider<NavigationController> navigationControllerProvider;

  private final Provider<Connectivity> connectivityProvider;

  private final Provider<SharedPreferences> prefProvider;

  public PSFragment_MembersInjector(Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<Connectivity> connectivityProvider, Provider<SharedPreferences> prefProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.navigationControllerProvider = navigationControllerProvider;
    this.connectivityProvider = connectivityProvider;
    this.prefProvider = prefProvider;
  }

  public static MembersInjector<PSFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<Connectivity> connectivityProvider, Provider<SharedPreferences> prefProvider) {
    return new PSFragment_MembersInjector(viewModelFactoryProvider, navigationControllerProvider, connectivityProvider, prefProvider);
  }

  @Override
  public void injectMembers(PSFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
    injectNavigationController(instance, navigationControllerProvider.get());
    injectConnectivity(instance, connectivityProvider.get());
    injectPref(instance, prefProvider.get());
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.common.PSFragment.viewModelFactory")
  public static void injectViewModelFactory(PSFragment instance,
      ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.common.PSFragment.navigationController")
  public static void injectNavigationController(PSFragment instance,
      NavigationController navigationController) {
    instance.navigationController = navigationController;
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.common.PSFragment.connectivity")
  public static void injectConnectivity(PSFragment instance, Connectivity connectivity) {
    instance.connectivity = connectivity;
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.common.PSFragment.pref")
  public static void injectPref(PSFragment instance, SharedPreferences pref) {
    instance.pref = pref;
  }
}
