// Generated by Dagger (https://dagger.dev).
package com.panaceasoft.psbuyandsell.ui.language;

import android.content.SharedPreferences;
import androidx.lifecycle.ViewModelProvider;
import com.panaceasoft.psbuyandsell.ui.common.NavigationController;
import com.panaceasoft.psbuyandsell.ui.common.PSFragment_MembersInjector;
import com.panaceasoft.psbuyandsell.utils.Connectivity;
import dagger.MembersInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LanguageFragment_MembersInjector implements MembersInjector<LanguageFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  private final Provider<NavigationController> navigationControllerProvider;

  private final Provider<Connectivity> connectivityProvider;

  private final Provider<SharedPreferences> prefProvider;

  private final Provider<SharedPreferences> sharedPreferencesProvider;

  public LanguageFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<Connectivity> connectivityProvider, Provider<SharedPreferences> prefProvider,
      Provider<SharedPreferences> sharedPreferencesProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.navigationControllerProvider = navigationControllerProvider;
    this.connectivityProvider = connectivityProvider;
    this.prefProvider = prefProvider;
    this.sharedPreferencesProvider = sharedPreferencesProvider;
  }

  public static MembersInjector<LanguageFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<Connectivity> connectivityProvider, Provider<SharedPreferences> prefProvider,
      Provider<SharedPreferences> sharedPreferencesProvider) {
    return new LanguageFragment_MembersInjector(viewModelFactoryProvider, navigationControllerProvider, connectivityProvider, prefProvider, sharedPreferencesProvider);
  }

  @Override
  public void injectMembers(LanguageFragment instance) {
    PSFragment_MembersInjector.injectViewModelFactory(instance, viewModelFactoryProvider.get());
    PSFragment_MembersInjector.injectNavigationController(instance, navigationControllerProvider.get());
    PSFragment_MembersInjector.injectConnectivity(instance, connectivityProvider.get());
    PSFragment_MembersInjector.injectPref(instance, prefProvider.get());
    injectSharedPreferences(instance, sharedPreferencesProvider.get());
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.language.LanguageFragment.sharedPreferences")
  public static void injectSharedPreferences(LanguageFragment instance,
      SharedPreferences sharedPreferences) {
    instance.sharedPreferences = sharedPreferences;
  }
}
