// Generated by Dagger (https://dagger.dev).
package com.prospective.tractorplus.ui.city.selectedcity;

import android.content.SharedPreferences;
import androidx.lifecycle.ViewModelProvider;
import com.prospective.tractorplus.ui.common.NavigationController;
import com.prospective.tractorplus.ui.common.PSAppCompactActivity_MembersInjector;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SelectedCityActivity_MembersInjector implements MembersInjector<SelectedCityActivity> {
  private final Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider;

  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  private final Provider<NavigationController> navigationControllerProvider;

  private final Provider<SharedPreferences> prefProvider;

  public SelectedCityActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<SharedPreferences> prefProvider) {
    this.dispatchingAndroidInjectorProvider = dispatchingAndroidInjectorProvider;
    this.viewModelFactoryProvider = viewModelFactoryProvider;
    this.navigationControllerProvider = navigationControllerProvider;
    this.prefProvider = prefProvider;
  }

  public static MembersInjector<SelectedCityActivity> create(
      Provider<DispatchingAndroidInjector<Object>> dispatchingAndroidInjectorProvider,
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider,
      Provider<NavigationController> navigationControllerProvider,
      Provider<SharedPreferences> prefProvider) {
    return new SelectedCityActivity_MembersInjector(dispatchingAndroidInjectorProvider, viewModelFactoryProvider, navigationControllerProvider, prefProvider);
  }

  @Override
  public void injectMembers(SelectedCityActivity instance) {
    PSAppCompactActivity_MembersInjector.injectDispatchingAndroidInjector(instance, dispatchingAndroidInjectorProvider.get());
    PSAppCompactActivity_MembersInjector.injectViewModelFactory(instance, viewModelFactoryProvider.get());
    PSAppCompactActivity_MembersInjector.injectNavigationController(instance, navigationControllerProvider.get());
    injectPref(instance, prefProvider.get());
  }

  @InjectedFieldSignature("com.panaceasoft.psbuyandsell.ui.city.selectedcity.SelectedCityActivity.pref")
  public static void injectPref(SelectedCityActivity instance, SharedPreferences pref) {
    instance.pref = pref;
  }
}
